import { useState } from "react";
import { FiAlertTriangle, FiBell, FiCheckCircle, FiExternalLink, FiInfo, FiLoader, FiSearch, FiTrendingUp, FiXCircle } from "react-icons/fi";
import type { BrowserNotificationPermission } from "./browser-notification";
import { savedBuildMonitorAlertMatches } from "../shared/saved-build-monitor-alerts";
import type { SavedBuildMonitorAlert, SavedBuildMonitorAlertFilter } from "../shared/saved-build-monitor-alerts";
import { savedBuildMonitorSummaryForDisplay, savedBuildMonitorTitleForDisplay } from "../shared/saved-build-monitor-copy";

export function SavedBuildMonitorAlertsPanel({ alerts, availableBuildIds, openingBuildId, browserNotificationPermission, browserNotificationEnabled, onRequestBrowserNotifications, onBrowserNotificationsEnabledChange, onReadAll, onDismissAll, onDismiss, onOpenBuild }: { alerts: SavedBuildMonitorAlert[]; availableBuildIds: ReadonlySet<string>; openingBuildId: string | null; browserNotificationPermission: BrowserNotificationPermission; browserNotificationEnabled: boolean; onRequestBrowserNotifications: () => void; onBrowserNotificationsEnabledChange: (enabled: boolean) => void; onReadAll: () => void; onDismissAll: () => void; onDismiss: (id: string) => void; onOpenBuild: (alert: SavedBuildMonitorAlert, findingRuleId?: string) => void }) {
  const [filter, setFilter] = useState<SavedBuildMonitorAlertFilter>("all");
  const unreadCount = alerts.filter((alert) => !alert.readAt).length;
  const filterOptions: Array<{ id: SavedBuildMonitorAlertFilter; label: string }> = [{ id: "all", label: "전체" }, { id: "unread", label: "읽지 않음" }, { id: "attention", label: "먼저 확인" }, { id: "changes", label: "정보 변화" }];
  const filteredAlerts = alerts.filter((alert) => savedBuildMonitorAlertMatches(alert, filter));
  return <section className="history-monitor-alerts" aria-label="저장 견적 알림" data-testid="saved-build-monitor-alerts">
    <div className="history-monitor-alerts-heading">
      <div><h2><FiBell /> 저장 견적 알림함{unreadCount > 0 ? ` · 읽지 않음 ${unreadCount}` : ""}</h2><p>가격이나 호환 정보가 달라지면 알려드려요. 알림은 이 브라우저에 저장됩니다.</p></div>
      <div><button className="text-button" type="button" onClick={onReadAll} disabled={unreadCount === 0}>모두 읽음</button><button className="text-button danger-text-button" type="button" onClick={onDismissAll} disabled={alerts.length === 0}>알림 지우기</button></div>
    </div>
    <div className="history-monitor-alert-filters" role="group" aria-label="저장 견적 알림 필터">{filterOptions.map((option) => <button className={filter === option.id ? "selected" : ""} type="button" aria-pressed={filter === option.id} data-testid={`saved-build-alert-filter-${option.id}`} onClick={() => setFilter(option.id)} key={option.id}>{option.label}<span>{alerts.filter((alert) => savedBuildMonitorAlertMatches(alert, option.id)).length}</span></button>)}</div>
    <div className="history-monitor-browser-notifications"><FiBell /><div><strong>브라우저 알림</strong><small>페이지가 열려 있을 때 새 호환 문제나 가격 변화가 생기면 알려드려요.</small></div>{browserNotificationPermission === "unsupported" ? <span className="history-monitor-browser-notification-status">이 브라우저에서는 사용할 수 없어요.</span> : browserNotificationPermission === "denied" ? <span className="history-monitor-browser-notification-status denied">브라우저에서 거부됨 · 설정에서 바꿀 수 있어요.</span> : browserNotificationPermission === "default" ? <button className="text-button" type="button" onClick={onRequestBrowserNotifications}>브라우저 알림 켜기</button> : <label><input type="checkbox" aria-label="저장 견적 브라우저 알림 사용" checked={browserNotificationEnabled} onChange={(event) => onBrowserNotificationsEnabledChange(event.target.checked)} /><span>{browserNotificationEnabled ? "사용 중" : "꺼짐"}</span></label>}</div>
    {alerts.length === 0 ? <div className="history-monitor-alerts-empty"><FiCheckCircle /><div><strong>새 알림이 없습니다.</strong><span>같은 상태가 이어지는 동안에는 알림을 반복해 보여주지 않아요.</span></div></div> : filteredAlerts.length === 0 ? <div className="history-monitor-alerts-empty"><FiSearch /><div><strong>선택한 조건의 알림이 없습니다.</strong><span>다른 항목을 선택해 주세요.</span></div></div> : <div className="history-monitor-alert-list" aria-live="polite">{filteredAlerts.map((alert) => {
      const AlertIcon = alert.kind === "critical" || alert.kind === "review" ? FiAlertTriangle : alert.kind === "failed" ? FiXCircle : alert.kind === "improved" ? FiCheckCircle : alert.kind === "alternative" ? FiTrendingUp : FiBell;
      return <article className={`history-monitor-alert ${alert.kind}${alert.readAt ? " read" : ""}`} key={alert.id}>
        <AlertIcon />
        <div><div className="history-monitor-alert-title"><strong>{alert.buildName}</strong><span>{savedBuildMonitorTitleForDisplay(alert.title)}</span></div><p>{savedBuildMonitorSummaryForDisplay(alert.message)}</p>{alert.alternative && <div className="history-monitor-alert-alternative"><div><span>현재 부품</span><strong>{alert.alternative.currentPartName}</strong>{alert.alternative.currentPriceWon !== undefined && <small>{alert.alternative.currentPriceWon.toLocaleString("ko-KR")}원</small>}</div><b>→</b><div><span>추천 대안</span><strong>{alert.alternative.candidatePartName}</strong>{alert.alternative.candidatePriceWon !== undefined && <small>{alert.alternative.candidatePriceWon.toLocaleString("ko-KR")}원</small>}</div>{alert.alternative.priceDeltaWon !== undefined && <em>{alert.alternative.priceDeltaWon < 0 ? `${Math.abs(alert.alternative.priceDeltaWon).toLocaleString("ko-KR")}원 절약` : `가격 ${alert.alternative.priceDeltaWon > 0 ? "+" : ""}${alert.alternative.priceDeltaWon.toLocaleString("ko-KR")}원`}</em>}</div>}{alert.findingTitles && alert.findingTitles.length > 0 && <div className="history-monitor-alert-findings"><span>영향 항목 · 제목을 누르면 상세로 이동</span><div>{alert.findingTitles.map((title, index) => { const findingRuleId = alert.findingRuleIds?.[index]; return findingRuleId ? <button className="history-monitor-alert-finding-link" type="button" onClick={() => onOpenBuild(alert, findingRuleId)} disabled={openingBuildId !== null} key={`${findingRuleId}-${title}`}>{title}</button> : <em key={title}>{title}</em>; })}</div></div>}<small>감지 {new Date(alert.createdAt).toLocaleString("ko-KR")}{alert.checkedAt ? ` · 확인 ${new Date(alert.checkedAt).toLocaleString("ko-KR")}` : ""}</small></div>
        <div className="history-monitor-alert-actions">{availableBuildIds.has(alert.buildId) && <button className="text-button" type="button" onClick={() => onOpenBuild(alert)} disabled={openingBuildId !== null}>{openingBuildId === alert.buildId ? <><FiLoader className="spin" /> 불러오는 중...</> : <><FiExternalLink /> 견적 보기</>}</button>}<button className="text-button" type="button" aria-label={`${alert.buildName} ${savedBuildMonitorTitleForDisplay(alert.title)} 알림 지우기`} onClick={() => onDismiss(alert.id)} disabled={openingBuildId !== null}>지우기</button></div>
      </article>;
    })}</div>}
    <p className="history-monitor-alerts-note"><FiInfo /> 이 알림은 현재 브라우저에 저장됩니다. 알림을 지우면 내용이 다시 바뀔 때까지 표시되지 않아요.</p>
  </section>;
}
