import { useState } from "react";
import { FiAlertTriangle, FiBell, FiCheckCircle, FiExternalLink, FiInfo, FiLoader, FiSearch, FiTrendingUp, FiXCircle } from "react-icons/fi";
import type { BrowserNotificationPermission } from "./browser-notification";
import { savedBuildMonitorAlertMatches } from "../shared/saved-build-monitor-alerts";
import type { SavedBuildMonitorAlert, SavedBuildMonitorAlertFilter } from "../shared/saved-build-monitor-alerts";

export function SavedBuildMonitorAlertsPanel({ alerts, availableBuildIds, openingBuildId, browserNotificationPermission, browserNotificationEnabled, onRequestBrowserNotifications, onBrowserNotificationsEnabledChange, onReadAll, onDismissAll, onDismiss, onOpenBuild }: { alerts: SavedBuildMonitorAlert[]; availableBuildIds: ReadonlySet<string>; openingBuildId: string | null; browserNotificationPermission: BrowserNotificationPermission; browserNotificationEnabled: boolean; onRequestBrowserNotifications: () => void; onBrowserNotificationsEnabledChange: (enabled: boolean) => void; onReadAll: () => void; onDismissAll: () => void; onDismiss: (id: string) => void; onOpenBuild: (alert: SavedBuildMonitorAlert, findingRuleId?: string) => void }) {
  const [filter, setFilter] = useState<SavedBuildMonitorAlertFilter>("all");
  const unreadCount = alerts.filter((alert) => !alert.readAt).length;
  const filterOptions: Array<{ id: SavedBuildMonitorAlertFilter; label: string }> = [{ id: "all", label: "전체" }, { id: "unread", label: "미읽음" }, { id: "attention", label: "즉시 확인" }, { id: "changes", label: "정보 변화" }];
  const filteredAlerts = alerts.filter((alert) => savedBuildMonitorAlertMatches(alert, filter));
  return <section className="history-monitor-alerts" aria-label="저장 견적 위험 변화 알림함" data-testid="saved-build-monitor-alerts">
    <div className="history-monitor-alerts-heading">
      <div><p className="eyebrow">RISK CHANGE INBOX</p><h2><FiBell /> 저장 견적 알림함{unreadCount > 0 ? ` · 미읽음 ${unreadCount}` : ""}</h2><p>자동·수동 전체 점검에서 새로 감지한 위험과 정보 변화를 이 브라우저에만 보관합니다.</p></div>
      <div><button className="text-button" type="button" onClick={onReadAll} disabled={unreadCount === 0}>모두 읽음</button><button className="text-button danger-text-button" type="button" onClick={onDismissAll} disabled={alerts.length === 0}>알림 지우기</button></div>
    </div>
    <div className="history-monitor-alert-filters" role="group" aria-label="저장 견적 알림 필터">{filterOptions.map((option) => <button className={filter === option.id ? "selected" : ""} type="button" aria-pressed={filter === option.id} data-testid={`saved-build-alert-filter-${option.id}`} onClick={() => setFilter(option.id)} key={option.id}>{option.label}<span>{alerts.filter((alert) => savedBuildMonitorAlertMatches(alert, option.id)).length}</span></button>)}</div>
    <div className="history-monitor-browser-notifications"><FiBell /><div><strong>브라우저 데스크톱 알림</strong><small>페이지가 열려 있고 새 위험이 생길 때만 이 기기에 표시합니다. 권한은 자동으로 요청하지 않습니다.</small></div>{browserNotificationPermission === "unsupported" ? <span className="history-monitor-browser-notification-status">이 브라우저는 지원하지 않음</span> : browserNotificationPermission === "denied" ? <span className="history-monitor-browser-notification-status denied">차단됨 · 브라우저 설정에서 허용</span> : browserNotificationPermission === "default" ? <button className="text-button" type="button" onClick={onRequestBrowserNotifications}>브라우저 알림 허용</button> : <label><input type="checkbox" aria-label="저장 견적 브라우저 알림 사용" checked={browserNotificationEnabled} onChange={(event) => onBrowserNotificationsEnabledChange(event.target.checked)} /><span>{browserNotificationEnabled ? "사용 중" : "꺼짐"}</span></label>}</div>
    {alerts.length === 0 ? <div className="history-monitor-alerts-empty"><FiCheckCircle /><div><strong>새로운 저장 견적 알림이 없습니다.</strong><span>같은 상태의 반복 점검은 새 알림으로 쌓이지 않습니다.</span></div></div> : filteredAlerts.length === 0 ? <div className="history-monitor-alerts-empty"><FiSearch /><div><strong>선택한 조건의 알림이 없습니다.</strong><span>다른 필터를 선택하거나 다음 점검 결과를 기다려 주세요.</span></div></div> : <div className="history-monitor-alert-list" aria-live="polite">{filteredAlerts.map((alert) => {
      const AlertIcon = alert.kind === "critical" || alert.kind === "review" ? FiAlertTriangle : alert.kind === "failed" ? FiXCircle : alert.kind === "improved" ? FiCheckCircle : alert.kind === "alternative" ? FiTrendingUp : FiBell;
      return <article className={`history-monitor-alert ${alert.kind}${alert.readAt ? " read" : ""}`} key={alert.id}>
        <AlertIcon />
        <div><div className="history-monitor-alert-title"><strong>{alert.buildName}</strong><span>{alert.title}</span></div><p>{alert.message}</p>{alert.findingTitles && alert.findingTitles.length > 0 && <div className="history-monitor-alert-findings"><span>영향 항목 · 제목을 누르면 상세로 이동</span><div>{alert.findingTitles.map((title, index) => { const findingRuleId = alert.findingRuleIds?.[index]; return findingRuleId ? <button className="history-monitor-alert-finding-link" type="button" onClick={() => onOpenBuild(alert, findingRuleId)} disabled={openingBuildId !== null} key={`${findingRuleId}-${title}`}>{title}</button> : <em key={title}>{title}</em>; })}</div></div>}<small>감지 {new Date(alert.createdAt).toLocaleString("ko-KR")}{alert.checkedAt ? ` · 검사 ${new Date(alert.checkedAt).toLocaleString("ko-KR")}` : ""}</small></div>
        <div className="history-monitor-alert-actions">{availableBuildIds.has(alert.buildId) && <button className="text-button" type="button" onClick={() => onOpenBuild(alert)} disabled={openingBuildId !== null}>{openingBuildId === alert.buildId ? <><FiLoader className="spin" /> 불러오는 중...</> : <><FiExternalLink /> 견적 보기</>}</button>}<button className="text-button" type="button" aria-label={`${alert.buildName} ${alert.title} 알림 지우기`} onClick={() => onDismiss(alert.id)} disabled={openingBuildId !== null}>지우기</button></div>
      </article>;
    })}</div>}
    <p className="history-monitor-alerts-note"><FiInfo /> 외부 푸시·이메일 알림이 아니며, 서버 검사 이력과 분리된 브라우저 알림입니다. 지운 신호는 상태가 달라지기 전까지 다시 표시하지 않습니다.</p>
  </section>;
}
